FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm config set registry https://registry.npmmirror.com && npm install
COPY . .
RUN npm run build

FROM node:20-alpine
RUN npm config set registry https://registry.npmmirror.com && npm install -g serve
COPY --from=builder /app/dist /app/dist
EXPOSE 3001
CMD ["serve", "-s", "/app/dist", "-l", "3001"]
