"""add duckdb_path to sources

Revision ID: ef38ccc0575d
Revises: d700d4cb67d9
Create Date: 2026-03-09 04:00:45.493321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef38ccc0575d'
down_revision: Union[str, None] = 'd700d4cb67d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('duckdb_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'duckdb_path')
    # ### end Alembic commands ###
